name: distance1
version: 'master'
summary: distance1
description: |
  This snap reads distance from the obstacle. 

grade: stable
confinement: strict

apps:
 distance1:
   command: python3 HCSR04Test.py
   daemon: simple
   plugs: [gpio-memory-control] 

parts:
   distance1:
       plugin: python
       python-version: python3
       python-packages: [RPi.GPIO]
       source: .